apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pfbd-rep2
provisioner: pfbd.csi.pureflash
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  replica_count: "2"

